// Seed-based wallet lifecycle for the headless CLI. Adapted from the
// mnf-se-examples `@mnf-se/common` package (wallet-sdk-facade 3.0.0 line).
import * as ledger from '@midnight-ntwrk/ledger-v8';
import { nativeToken } from '@midnight-ntwrk/ledger-v8';
import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  createKeystore,
  InMemoryTransactionHistoryStorage,
  PublicKey,
  UnshieldedWallet,
  type UnshieldedKeystore,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { getNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import type { MidnightProvider, WalletProvider, UnboundTransaction } from '@midnight-ntwrk/midnight-js-types';
import * as Rx from 'rxjs';
import type { Config } from './config.js';
import { log, withStatus } from './display.js';

export interface WalletContext {
  wallet: WalletFacade;
  shieldedSecretKeys: ledger.ZswapSecretKeys;
  dustSecretKey: ledger.DustSecretKey;
  unshieldedKeystore: UnshieldedKeystore;
  address: string;
}

export const deriveKeysFromSeed = (seedHex: string) => {
  const hdWallet = HDWallet.fromSeed(Buffer.from(seedHex, 'hex'));
  if (hdWallet.type !== 'seedOk') throw new Error('Failed to initialize HDWallet from seed');
  const derived = hdWallet.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  if (derived.type !== 'keysDerived') throw new Error('Failed to derive keys');
  hdWallet.hdWallet.clear();
  return derived.keys;
};

export const buildWallet = async (config: Config, seedHex: string, label: string): Promise<WalletContext> => {
  const keys = deriveKeysFromSeed(seedHex);
  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], getNetworkId());

  const indexerClientConnection = { indexerHttpUrl: config.indexer, indexerWsUrl: config.indexerWS };
  const networkId = getNetworkId();
  const shieldedConfig = {
    networkId,
    indexerClientConnection,
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, 'ws')),
  };
  const unshieldedConfig = {
    networkId,
    indexerClientConnection,
    txHistoryStorage: new InMemoryTransactionHistoryStorage(),
  };
  const dustConfig = {
    networkId,
    costParameters: { additionalFeeOverhead: 300_000_000_000_000n, feeBlocksMargin: 5 },
    indexerClientConnection,
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, 'ws')),
  };

  const wallet = await WalletFacade.init({
    configuration: { ...shieldedConfig, ...unshieldedConfig, ...dustConfig },
    shielded: () => ShieldedWallet(shieldedConfig).startWithSecretKeys(shieldedSecretKeys),
    unshielded: () =>
      UnshieldedWallet(unshieldedConfig).startWithPublicKey(PublicKey.fromKeyStore(unshieldedKeystore)),
    dust: () =>
      DustWallet(dustConfig).startWithSecretKey(dustSecretKey, ledger.LedgerParameters.initialParameters().dust),
  });
  await wallet.start(shieldedSecretKeys, dustSecretKey);

  const address = unshieldedKeystore.getBech32Address().toString();
  log(`${label}: ${address}`);
  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore, address };
};

export const waitForSync = (wallet: WalletFacade) =>
  Rx.firstValueFrom(wallet.state().pipe(Rx.throttleTime(3_000), Rx.filter((s) => s.isSynced)));

export const nightBalance = async (wallet: WalletFacade): Promise<bigint> => {
  const s = await Rx.firstValueFrom(wallet.state().pipe(Rx.filter((st) => st.isSynced)));
  return s.unshielded.balances[nativeToken().raw] ?? 0n;
};

export const dustBalance = async (wallet: WalletFacade): Promise<bigint> => {
  const s = await Rx.firstValueFrom(wallet.state().pipe(Rx.filter((st) => st.isSynced)));
  return s.dust.balance(new Date());
};

/** Wait until the wallet holds NIGHT (funded by faucet or by a transfer). */
export const waitForFunds = (wallet: WalletFacade): Promise<bigint> =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(5_000),
      Rx.filter((s) => s.isSynced),
      Rx.map((s) => s.unshielded.balances[nativeToken().raw] ?? 0n),
      Rx.filter((b) => b > 0n),
    ),
  );

/**
 * DUST is mandatory for every transaction and is only generated by NIGHT
 * UTXOs that have been explicitly registered. Register any unregistered
 * UTXOs, then wait for a non-zero DUST balance.
 */
export const ensureDust = async (ctx: WalletContext): Promise<bigint> => {
  const state = await Rx.firstValueFrom(ctx.wallet.state().pipe(Rx.filter((s) => s.isSynced)));
  if (state.dust.balance(new Date()) > 0n) return state.dust.balance(new Date());

  const unregistered = state.unshielded.availableCoins.filter(
    (coin: { meta?: { registeredForDustGeneration?: boolean } }) => coin.meta?.registeredForDustGeneration !== true,
  );
  if (unregistered.length > 0) {
    await withStatus(`Registering ${unregistered.length} NIGHT UTXO(s) for DUST generation`, async () => {
      const recipe = await ctx.wallet.registerNightUtxosForDustGeneration(
        unregistered,
        ctx.unshieldedKeystore.getPublicKey(),
        (payload) => ctx.unshieldedKeystore.signData(payload),
      );
      const finalized = await ctx.wallet.finalizeRecipe(recipe);
      await ctx.wallet.submitTransaction(finalized);
    });
  }
  return withStatus('Waiting for DUST to generate', () =>
    Rx.firstValueFrom(
      ctx.wallet.state().pipe(
        Rx.throttleTime(5_000),
        Rx.filter((s) => s.isSynced),
        Rx.map((s) => s.dust.balance(new Date())),
        Rx.filter((b) => b > 0n),
      ),
    ),
  );
};

/** Bridge wallet-sdk-facade to midnight-js's WalletProvider + MidnightProvider. */
export const createWalletAndMidnightProvider = async (ctx: WalletContext): Promise<WalletProvider & MidnightProvider> => {
  await Rx.firstValueFrom(ctx.wallet.state().pipe(Rx.filter((s) => s.isSynced)));
  return {
    getCoinPublicKey(): ledger.CoinPublicKey {
      return ctx.shieldedSecretKeys.coinPublicKey;
    },
    getEncryptionPublicKey(): ledger.EncPublicKey {
      return ctx.shieldedSecretKeys.encryptionPublicKey;
    },
    async balanceTx(tx: UnboundTransaction, ttl?: Date): Promise<ledger.FinalizedTransaction> {
      const recipe = await ctx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: ctx.shieldedSecretKeys, dustSecretKey: ctx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return await ctx.wallet.finalizeRecipe(recipe);
    },
    async submitTx(tx: ledger.FinalizedTransaction): Promise<ledger.TransactionId> {
      return await ctx.wallet.submitTransaction(tx);
    },
  };
};
